version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8081:80"
        restart: always
        volumes:
            - ../public:/var/www/html
            - ../etc/nginx/logs/:/var/log/nginx/
            - ../etc/nginx/sites-enabled/:/etc/nginx/conf.d/
        command: [nginx-debug, '-g', 'daemon off;']
        depends_on:
            - php
            - mariadb
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "9000:9000"
            - "8000:8000"
            - "8082:8082"
            - "5173:5173"
        restart: always
        volumes:
            - ../public:/var/www/html
            - ../php/conf.d/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini
            - ../php/conf.d/90-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini       
            - ../php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ../php/xdebug/log/xdebug-codeigniter.log:/tmp/xdebug/xdebug-codeigniter.log
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ../data/mariadb:/var/lib/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: limpeza
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        ports:
            - "8080:80"
        restart: always
        depends_on:
            - mariadb
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mariadb
